(defun operacion-compleja (a b c)
  (let ((resultado1 (* a b))
        (resultado2 (+ b c)))
    (/ resultado1 resultado2)))

(defun ejemplo-metodo-complejo ()
  (let ((valor1 5)
        (valor2 10)
        (valor3 3))
    (operacion-compleja valor1 valor2 valor3)))
